import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from '@/components/ui/sonner';

const Nacelle = localFont({
  src: '../public/fonts/Nacelle-Regular.woff2',
  variable: '--font-Nacelle',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${Nacelle.variable} no-scrollbar h-screen w-screen bg-background font-nacelle antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          disableTransitionOnChange
          enableSystem
        >
          <main className='flex h-full w-full flex-col justify-between'>
            {children}
          </main>
        </ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
