import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { Toaster } from '@/components/ui/sonner';

const Nacelle = localFont({
  src: '../public/fonts/Nacelle-Regular.woff2',
  variable: '--font-Nacelle',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Nacelle.variable} antialiased`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
